AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  CodeDeployServiceRoleArn:
    Description: Code deploy service role arn
    Export:
      Name: {'Fn::Sub': '${AWS::StackName}-CodeDeployServiceRoleArn'}
    Value: {'Fn::GetAtt': CodeDeployServiceRole.Arn}
Resources:
  CodeDeployServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codedeploy.us-west-2.amazonaws.com]
        Version: 2012-10-17
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole']
      RoleName: CodeDeployServiceRole
    Type: AWS::IAM::Role
  
